apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: nodeapp
build:
  artifacts:
    - image: nodeapp
deploy:
  kubectl:
    manifests:
      - k8s/*.yml # Path to your Kubernetes deployment manifests
