apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-internal
  labels:
    name: nodeapp-service-internal
spec:
  selector:
    app: nodeapp-label # Assuming "app" is a label key and "nodeapp-label" is the label value
  ports:
    - port: 3003 # this is the port of internal service
      targetPort: 3003
