apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-external
  labels:
    name: nodeapp-service-external
spec:
  type: NodePort
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30183
  selector:
    app: nodeapp-label
